// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvoxubhktdiiiiqexfdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52b3h1YmhrdGRpaWlpcWV4ZmRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNzY1MDcsImV4cCI6MjA3MDY1MjUwN30.V-2ajoXumSJw6UTvsjvnXbbHEfRKflv3FAa-eNf4ymA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});